name: Linter validation

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm i
      - name:  Build
        run: npx eslint . --ext .js,.jsx,.ts,.tsx 
        env:
          CI: true
